---
- name: Setup Docker on Alpine in VM
  hosts: localhost
  connection: local
  tasks:
  - name: Update packages and install docker
    community.general.apk:
      name: bash,docker,docker-compose,tailscale
      update_cache: true
  - name: Download setup_alpine_kopia.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/shell/setup_alpine_kopia.sh
      dest: /run/setup_alpine_kopia.sh
      mode: '0440'
  - name: Run setup_alpine_kopia.sh
    command: bash /run/setup_alpine_kopia.sh
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
  - name: Create "/opt/docker/stacks" directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/stacks' directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  - name: Create "/opt/docker/volumes" directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/volumes' directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  - name: Enabled and start docker service
    ansible.builtin.service:
      name: docker
      enabled: yes
      state: started
  - name: Enabled and start tailscale service
    ansible.builtin.service:
      name: tailscale
      enabled: yes
      state: started
  