---
- name: Setup Docker on Alpine in LXC
  hosts: localhost
  connection: local
  tasks:
  - name: Update packages and install docker
    community.general.apk:
      name: docker,docker-compose,tailscale
      update_cache: true
  - name: Enabled and start docker service
    ansible.builtin.service:
      name: docker
      enabled: yes
      state: started
  - name: Enabled and start tailscale service
    ansible.builtin.service:
      name: tailscale
      enabled: yes
      state: started
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
  - name: Create "docker" directory
    ansible.builtin.file:
      path: /opt/docker
      state: directory
      mode: '0755'
  - name: Recursively change ownership of 'docker' directory
    ansible.builtin.file:
      path: /opt/docker
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  - name: Create "docker-data" directory
    ansible.builtin.file:
      path: /opt/docker-data
      state: directory
      mode: '0755'
  - name: Recursively change ownership of 'docker-data' directory
    ansible.builtin.file:
      path: /opt/docker-data
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  