#cloud-config
locale: en_US
timezone: "Europe/Budapest"
package_update: true
package_upgrade: true
packages:
  - ansible
runcmd:
  - [ wget, "https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/alpine.yml", -O, "/run/alpine.yml" ]
  - [ ansible-playbook, /run/alpine.yml ]