---
- name: Setup Alpine in LXC
  hosts: localhost
  connection: local

  tasks:
  - name: Update packages and install docker
    community.general.apk:
      name: docker,docker-compose
      update_cache: true
  - name: Enabled and start docker service
    ansible.builtin.service:
      name: docker
      enabled: yes
      state: started