---
- name: Setup Alpine in LXC
  hosts: localhost
  connection: local

  tasks:
  - name: Update packages and install docker
    community.general.apk:
      name: sudo,docker,docker-compose
      update_cache: true
  - name: Enabled and start docker service
    ansible.builtin.service:
      name: docker
      enabled: yes
      state: started
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
  - name: Create "services" directory
    ansible.builtin.file:
      path: /home/tartarus/services
      state: directory
      mode: '0755'
  - name: Recursively change ownership of 'services' directory
    ansible.builtin.file:
      path: /home/tartarus/services
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus