---
- name: Setup Docker on Debian in VM
  hosts: localhost
  connection: local
  tasks:
  - name: Download setup_debian_docker.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/shell/setup_debian_docker.sh
      dest: /run/setup_debian_docker.sh
      mode: '0440'
  - name: Install docker
    command: bash /run/setup_debian_docker.sh
  - name: Download setup_debian_kopia.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/shell/setup_debian_kopia.sh
      dest: /run/setup_debian_kopia.sh
      mode: '0440'
  - name: Install kopia
    command: bash /run/setup_debian_kopia.sh
  - name: Download setup_tailscale.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/shell/setup_tailscale.sh
      dest: /run/setup_tailscale.sh
      mode: '0440'
  - name: Install tailscale
    command: bash /run/setup_tailscale.sh
    
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
      shell: /bin/bash
  - name: Create "/opt/docker/stacks" directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/stacks' directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  - name: Create "/opt/docker/volumes" directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/volumes' directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus