---
- name: Setup Docker on Debian in VM
  hosts: localhost
  connection: local
  tasks:
  - name: Update repositories cache and install firewall and unattended upgrades
    ansible.builtin.apt:
      name: ufw,unattended-upgrades,apt-config-auto-update
      update_cache: yes
  - name: Put docker behind ufw
    ansible.builtin.blockinfile:
      path: /etc/ufw/after.rules
      block: |
        # Put Docker behind UFW
        *filter
        :DOCKER-USER - [0:0]
        :ufw-user-input - [0:0]

        -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
        -A DOCKER-USER -m conntrack --ctstate INVALID -j DROP
        -A DOCKER-USER -i eth0 -j ufw-user-input
        -A DOCKER-USER -i eth0 -j DROP
        COMMIT
  - name: Clean up custom rules in order to mess with the ufw reload
    ansible.builtin.blockinfile:
      path: /etc/ufw/before.init
      insertafter: 'stop\)'
      block: |
        iptables -F DOCKER-USER || true
  - name: Changing perm of "/etc/ufw/before.init", adding "+x"
    file: dest=/etc/ufw/before.init mode=a+x
  - name: Setup UFW rules
    ansible.builtin.shell: |
      ufw disable
      ufw enable
      ufw default deny incoming
      ufw default allow outgoing
      ufw allow in on tailscale0 from 100.64.1.1 proto tcp to any port 22
      ufw allow in on tailscale0 from 100.80.100.101 proto tcp to any port 80
      ufw allow in on tailscale0 from 100.80.100.102 proto tcp to any port 80
      ufw allow in on tailscale0 from 100.80.100.103 proto tcp to any port 80
      ufw reload
  - name: Download setup_debian_docker.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/shell/setup_debian_docker.sh
      dest: /run/setup_debian_docker.sh
      mode: '0440'
  - name: Install docker
    command: bash /run/setup_debian_docker.sh
  - name: Download setup_tailscale.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/shell/setup_tailscale.sh
      dest: /run/setup_tailscale.sh
      mode: '0440'
  - name: Install tailscale
    command: bash /run/setup_tailscale.sh
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
      shell: /bin/bash
  - name: Create "/opt/docker/stacks" directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      mode: '0755'
  - name: Create "/opt/docker/volumes" directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker' directory
    ansible.builtin.file:
      path: /opt/docker
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus