---
- name: Setup Docker on Debian in LXC
  hosts: localhost
  connection: local
  tasks:
  - name: Download setup_debian_docker.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/setup_debian_docker.sh
      dest: /run/setup_debian_docker.sh
      mode: '0440'
  - name: Run setup_debian_docker.sh
    command: bash /run/setup_debian_docker.sh
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
  - name: Create "docker" directory
    ansible.builtin.file:
      path: /home/tartarus/docker
      state: directory
      mode: '0755'
  - name: Recursively change ownership of 'docker' directory
    ansible.builtin.file:
      path: /home/tartarus/docker
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  - name: Create "docker-data" directory
    ansible.builtin.file:
      path: /home/tartarus/docker-data
      state: directory
      mode: '0755'
  - name: Recursively change ownership of 'docker-data' directory
    ansible.builtin.file:
      path: /home/tartarus/docker-data
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  