---
- name: Setup Docker on Debian in LXC
  hosts: localhost
  connection: local
  tasks:
  - name: Download setup_debian_docker.sh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/setup_debian_docker.sh
      dest: /run/setup_debian_docker.sh
      mode: '0440'
  - name: Run setup_debian_docker.sh
    command: bash /run/setup_debian_docker.sh
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
  - name: Create "/opt/docker/stacks" directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/stacks' directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  - name: Create "/opt/docker/volumes" directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/volumes' directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus