---
- name: Setup Debian in VM
  hosts: localhost
  connection: local
  tasks:
  - name: Update apt repository
    ansible.builtin.apt:
      update_cache: yes
  - name: Install curl  (state=present is optional)
    ansible.builtin.apt:
      name: curl
      state: present
  - name: Add Kopia repo key
    command: curl -s https://kopia.io/signing-key | gpg --dearmor -o /etc/apt/keyrings/kopia-keyring.gpg
  - name: Add Kopia repo to source list
    command: echo "deb [signed-by=/etc/apt/keyrings/kopia-keyring.gpg] http://packages.kopia.io/apt/ stable main" | tee /etc/apt/sources.list.d/kopia.list
  - name: Update apt repository
    ansible.builtin.apt:
      update_cache: yes
  - name: Install kopia (state=present is optional)
    ansible.builtin.apt:
      name: kopia
      state: present
  - name: Create user "tartarus"
    ansible.builtin.user:
      name: tartarus
      uid: 4000
      groups: docker
  - name: Create "/opt/docker/stacks" directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/stacks' directory
    ansible.builtin.file:
      path: /opt/docker/stacks
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus
  - name: Create "/opt/docker/volumes" directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      mode: '0755'
  - name: Recursively change ownership of '/opt/docker/volumes' directory
    ansible.builtin.file:
      path: /opt/docker/volumes
      state: directory
      recurse: yes
      owner: tartarus
      group: tartarus