#cloud-config
locale: en_US.UTF-8
timezone: "Europe/Budapest"
package_update: true
package_upgrade: true
packages:
  - ansible
runcmd:
  - [ wget, "https://raw.githubusercontent.com/zbalint/ansible-playbooks/master/debian/debian.ansible.yml", -O, "/run/debian.ansible.yml" ]
  - [ ansible-playbook, /run/debian.ansible.yml ]